# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number({build_number: latest_testflight_build_number + 1})
    build_app(workspace: "UTA-TBIcare.xcworkspace", scheme: "UTA-TBIcare")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
